version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Nothing to do in this phase
  pre_build:
    commands:
      - echo Nothing to do in this phase
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - 'target/codemo.war'