version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in this phase
  pre_build:
    commands:
      - echo Nothing to do in this phase
  build:
    commands:
      - echo Build started on `date`
      - gradle clean buid
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - 'target/codemo.war'